meta_product_name: "Stupid Idea Generator"
meta_title: "Stupid Idea Generator - Un générateur d'idées pour lancer votre licorne"
meta_description: Un générateur d'idées plus stupides que la stupidité pour vous aider à trouver une idée de licorne qui vous rendra multimilliardaire."
meta_image: "cover.png" # should exist in `app/assets/images/`
